import{a as L,i as n,s as w}from"./assets/vendor-BpiDY1p_.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))s(e);new MutationObserver(e=>{for(const r of e)if(r.type==="childList")for(const l of r.addedNodes)l.tagName==="LINK"&&l.rel==="modulepreload"&&s(l)}).observe(document,{childList:!0,subtree:!0});function a(e){const r={};return e.integrity&&(r.integrity=e.integrity),e.referrerPolicy&&(r.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?r.credentials="include":e.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function s(e){if(e.ep)return;e.ep=!0;const r=a(e);fetch(e.href,r)}})();const b="46118726-f37cd2f98d2a6e2b7b3af8ac8",P="https://pixabay.com/api/";async function g(o,t){const a=new URLSearchParams({key:b,q:o,image_type:"photo",orientation:"horizontal",safesearch:!0,page:t,per_page:15});try{const{data:s}=await L(`${P}?${a}`);return s}catch(s){console.log(s),n.error({message:"Something went wrong. Please try again later"})}}function y(o){return o.map(({webformatURL:t,largeImageURL:a,likes:s,views:e,comments:r,downloads:l,tags:p})=>`<li class="gallery_item">
  <a href="${a}"><img src="${t}" alt="${p}"><ul>
    <li>Likes ${s}</li>
    <li>Views ${e}</li>
    <li>Comments ${r}</li>
    <li>Downloads ${l}</li>
  </ul></a>
 </li>`).join("")}const f=document.querySelector(".form"),m=document.querySelector(".gallery"),u=document.querySelector(".loader"),i=document.querySelector(".load-more");let d=1,c="";const h=new w(".gallery a");f.addEventListener("submit",S);async function S(o){if(o.preventDefault(),c=o.target.elements.state.value.trim(),console.log(c),d=1,m.innerHTML="",i.classList.add("is-hidden"),c===""){n.warning({message:"Please enter a search query"});return}u.style.display="block";try{const t=await g(c,d);if(t.hits.length===0){n.warning({message:"Sorry, there are no images matching your search query. Please try again!"});return}const a=y(t.hits);m.insertAdjacentHTML("beforeend",a),h.refresh(),t.totalHits>15?i.classList.remove("is-hidden"):i.classList.add("is-hidden")}catch(t){console.log(t),n.error({message:"Something went wrong. Please try again later"})}finally{u.style.display="none",f.reset()}}i.addEventListener("click",q);async function q(){d+=1,u.style.display="block";try{const o=await g(c,d),t=y(o.hits);m.insertAdjacentHTML("beforeend",t),h.refresh();const s=document.querySelector(".gallery_item").getBoundingClientRect().height;window.scrollBy({top:s*2,behavior:"smooth"}),Math.ceil(o.totalHits/15)===d?(i.classList.add("is-hidden"),n.info({message:"We're sorry, but you've reached the end of search results."})):i.classList.remove("is-hidden")}catch(o){console.log(o),n.error({message:"Something went wrong. Please try again later"})}finally{u.style.display="none"}}
//# sourceMappingURL=index.js.map
